### ISSUE TITLE
detect plugin manager services on their parent, rather than their service name

### ISSUE THREAD

**Issue by joachim-n** [drupal-code-builder/drupal-code-builder#24]
```
  validation.constraint:
    class: Drupal\Core\Validation\ConstraintManager
    parent: default_plugin_manager
    tags:
      - { name: plugin_manager_cache_clear }
  lock:
    class: Drupal\Core\Lock\DatabaseLockBackend
    arguments: ['@database']
    tags:
      - { name: backend_overridable }
    lazy: true
```

This doesn't get picked up because it doesn't use the standard form for a plugin manager service name.

What we could do instead -- assuming we can get that out of the service container -- is detect 'parent: default_plugin_manager'.
