### ISSUE TITLE
YAML merge doesn't preserve quotes on non-service values

### ISSUE THREAD

**Issue by joachim-n** [drupal-code-builder/drupal-code-builder#265]
E.g.

```
services:
  logger.channel.wsd_api_mysql:
    parent: logger.channel_base
    arguments: [wsd_api_mysql]
```

Original YAML file had quotes on the wsd_api_mysql argument:

```
services:
  logger.channel.wsd_api_mysql:
    parent: logger.channel_base
    arguments: [ 'wsd_api_mysql' ]
```
