### ISSUE TITLE
decorated services

### ISSUE THREAD

**Issue by joachim-n** [drupal-code-builder/drupal-code-builder#368]
e.g.

```
services:
  finders_facets.bundle_config_form_facets:
    class: Drupal\finders_facets\BundleConfigFormFacets
    decorates: Drupal\localgov_finders\BundleConfigForm
    arguments: ['@.inner']
```

and then:

```
  /**
   * ReadOnlyModeMethodFilter constructor.
   *
   * @param \Drupal\localgov_finders\BundleConfigForm $inner
   *   The decorated form alterer service.
   */
  public function __construct(
    protected BundleConfigForm $inner
    ) {
  }
```

and also needs the services from the decorated service class, ideally!
