### ISSUE TITLE
don't collect plugin types from deprecated services

### ISSUE THREAD

**Issue by joachim-n** [drupal-code-builder/drupal-code-builder#91]
Eg:

```
  plugin.manager.migrate.cckfield:
    class: Drupal\migrate_drupal\Plugin\MigrateCckFieldPluginManager
    arguments:
      - cckfield
      - '@container.namespaces'
      - '@cache.discovery'
      - '@module_handler'
      - '\Drupal\migrate_drupal\Annotation\MigrateCckField'
    deprecated: The "%service_id%" service is deprecated. You should use the 'plugin.manager.migrate.field' service instead. See https://www.drupal.org/node/2751897
```
